# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "azbench" # $ vagrant box add ../package.box --name azbench

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.56.10"
  end

  (1..3).each do |i|
    config.vm.define "vm-#{i}" do |vm|
      vm.vm.network "private_network", ip: "192.168.56.#{i+10}"
    end
  end
end
